POST http://localhost:8080/players
Content-Type: application/json

{
  "username": "john_doe",
  "pictureUrl": "https://example.com/pictures/john_doe.jpg"
}
###
POST http://localhost:8080/players
Content-Type: application/json

{
"username": "kkkk",
"pictureUrl": "5"
}

###

POST http://localhost:8080/players/buy-game/550e8400-e29b-41d4-a716-446655440010

### Mark Game as Favorite
POST http://localhost:8080/players/favorite-game/550e8400-e29b-41d4-a716-446655440010
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### Remove Game from Favorites
POST http://localhost:8080/players/unfavorite-game/550e8400-e29b-41d4-a716-446655440010
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...


