spring.application.name=platform-backend

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver