name: bandit-games 

services:
  app_postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    networks:
      - kdg-backend
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./init-scripts/sql:/docker-entrypoint-initdb.d

networks:
  kdg-backend:
    name: kdg-back-network
    driver: bridge


